API_KEY = 'OARriJ5XHzGv2uSTOKlvdMH1HxT5HTCVrXzrAhMycuYBsomJ34khn9n6I0Gyf0l7'
API_SECRET = 'VHIjMvMCj8CzGM8TqlePbhoLMz4nM9VeiaDL1Y6CPBN9u2LpvRnESGHRyaAp2zHP'
PAIR = 'xrpusdt'
PAIR_M = 'XRPUSDT'
PAIR_S = 'usdt'
PAIR_B = "xrp"
QUANTITY = '100'
DEBUG = True